default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dbalpha_development

test:
  <<: *default
  database: dbalpha_test

production:
  <<: *default
  database: dbalpha_production
  username: dbalpha
  password: <%= ENV['DBALPHA_DATABASE_PASSWORD'] %>
